const phrases = [
  { jp: "こんにちは", rom: "Konnichiwa", ar: "مرحباً" },
  { jp: "ありがとう", rom: "Arigatou", ar: "شكراً" },
  { jp: "おはようございます", rom: "Ohayou gozaimasu", ar: "صباح الخير" },
  { jp: "こんばんは", rom: "Konbanwa", ar: "مساء الخير" },
  { jp: "さようなら", rom: "Sayounara", ar: "إلى اللقاء" },
  { jp: "おやすみなさい", rom: "Oyasuminasai", ar: "تصبح على خير" },
  { jp: "すみません", rom: "Sumimasen", ar: "عذراً / لو سمحت" },
  { jp: "はい", rom: "Hai", ar: "نعم" },
  { jp: "いいえ", rom: "Iie", ar: "لا" },
  { jp: "わかります", rom: "Wakarimasu", ar: "أفهم" },
  { jp: "わかりません", rom: "Wakarimasen", ar: "لا أفهم" },
  { jp: "日本語が少し話せます", rom: "Nihongo ga sukoshi hanasemasu", ar: "أستطيع التحدث باليابانية قليلاً" },
  { jp: "これはいくらですか？", rom: "Kore wa ikura desu ka?", ar: "كم سعر هذا؟" },
  { jp: "トイレはどこですか？", rom: "Toire wa doko desu ka?", ar: "أين دورة المياه؟" },
  { jp: "助けてください！", rom: "Tasukete kudasai!", ar: "النجدة!" },
  { jp: "お願いします", rom: "Onegaishimasu", ar: "من فضلك" },
  { jp: "初めまして", rom: "Hajimemashite", ar: "تشرفت بلقائك" },
  { jp: "どういたしまして", rom: "Dou itashimashite", ar: "على الرحب والسعة" },
  { jp: "元気ですか？", rom: "Genki desu ka?", ar: "هل أنت بخير؟" },
  { jp: "元気です", rom: "Genki desu", ar: "أنا بخير" },
  { jp: "こんにちは", rom: "Konnichiwa", ar: "مرحباً" },
  { jp: "ありがとう", rom: "Arigatou", ar: "شكراً" },
  { jp: "おはようございます", rom: "Ohayou gozaimasu", ar: "صباح الخير" },
  { jp: "こんばんは", rom: "Konbanwa", ar: "مساء الخير" },
  { jp: "さようなら", rom: "Sayounara", ar: "إلى اللقاء" },
  { jp: "おやすみなさい", rom: "Oyasuminasai", ar: "تصبح على خير" },
  { jp: "すみません", rom: "Sumimasen", ar: "عذراً / لو سمحت" },
  { jp: "はい", rom: "Hai", ar: "نعم" },
  { jp: "いいえ", rom: "Iie", ar: "لا" },
  { jp: "わかります", rom: "Wakarimasu", ar: "أفهم" },
  { jp: "わかりません", rom: "Wakarimasen", ar: "لا أفهم" },
  { jp: "日本語が少し話せます", rom: "Nihongo ga sukoshi hanasemasu", ar: "أستطيع التحدث باليابانية قليلاً" },
  { jp: "これはいくらですか？", rom: "Kore wa ikura desu ka?", ar: "كم سعر هذا؟" },
  { jp: "トイレはどこですか？", rom: "Toire wa doko desu ka?", ar: "أين دورة المياه؟" },
  { jp: "助けてください！", rom: "Tasukete kudasai!", ar: "النجدة!" },
  { jp: "お願いします", rom: "Onegaishimasu", ar: "من فضلك" },
  { jp: "初めまして", rom: "Hajimemashite", ar: "تشرفت بلقائك" },
  { jp: "どういたしまして", rom: "Dou itashimashite", ar: "على الرحب والسعة" },
  { jp: "元気ですか？", rom: "Genki desu ka?", ar: "هل أنت بخير؟" },
  { jp: "元気です", rom: "Genki desu", ar: "أنا بخير" },
  { jp: "こんにちは", rom: "Konnichiwa", ar: "مرحباً" },
  { jp: "ありがとう", rom: "Arigatou", ar: "شكراً" },
  { jp: "おはようございます", rom: "Ohayou gozaimasu", ar: "صباح الخير" },
  { jp: "こんばんは", rom: "Konbanwa", ar: "مساء الخير" },
  { jp: "さようなら", rom: "Sayounara", ar: "إلى اللقاء" },
  { jp: "おやすみなさい", rom: "Oyasuminasai", ar: "تصبح على خير" },
  { jp: "すみません", rom: "Sumimasen", ar: "عذراً / لو سمحت" },
  { jp: "はい", rom: "Hai", ar: "نعم" },
  { jp: "いいえ", rom: "Iie", ar: "لا" },
  { jp: "わかります", rom: "Wakarimasu", ar: "أفهم" },
  { jp: "わかりません", rom: "Wakarimasen", ar: "لا أفهم" },
  { jp: "日本語が少し話せます", rom: "Nihongo ga sukoshi hanasemasu", ar: "أستطيع التحدث باليابانية قليلاً" },
  { jp: "これはいくらですか？", rom: "Kore wa ikura desu ka?", ar: "كم سعر هذا؟" },
  { jp: "トイレはどこですか？", rom: "Toire wa doko desu ka?", ar: "أين دورة المياه؟" },
  { jp: "助けてください！", rom: "Tasukete kudasai!", ar: "النجدة!" },
  { jp: "お願いします", rom: "Onegaishimasu", ar: "من فضلك" },
  { jp: "初めまして", rom: "Hajimemashite", ar: "تشرفت بلقائك" },
  { jp: "どういたしまして", rom: "Dou itashimashite", ar: "على الرحب والسعة" },
  { jp: "元気ですか？", rom: "Genki desu ka?", ar: "هل أنت بخير؟" },
  { jp: "元気です", rom: "Genki desu", ar: "أنا بخير" },
  { jp: "こんにちは", rom: "Konnichiwa", ar: "مرحباً" },
  { jp: "ありがとう", rom: "Arigatou", ar: "شكراً" },
  { jp: "おはようございます", rom: "Ohayou gozaimasu", ar: "صباح الخير" },
  { jp: "こんばんは", rom: "Konbanwa", ar: "مساء الخير" },
  { jp: "さようなら", rom: "Sayounara", ar: "إلى اللقاء" },
  { jp: "おやすみなさい", rom: "Oyasuminasai", ar: "تصبح على خير" },
  { jp: "すみません", rom: "Sumimasen", ar: "عذراً / لو سمحت" },
  { jp: "はい", rom: "Hai", ar: "نعم" },
  { jp: "いいえ", rom: "Iie", ar: "لا" },
  { jp: "わかります", rom: "Wakarimasu", ar: "أفهم" },
  { jp: "わかりません", rom: "Wakarimasen", ar: "لا أفهم" },
  { jp: "日本語が少し話せます", rom: "Nihongo ga sukoshi hanasemasu", ar: "أستطيع التحدث باليابانية قليلاً" },
  { jp: "これはいくらですか？", rom: "Kore wa ikura desu ka?", ar: "كم سعر هذا؟" },
  { jp: "トイレはどこですか？", rom: "Toire wa doko desu ka?", ar: "أين دورة المياه؟" },
  { jp: "助けてください！", rom: "Tasukete kudasai!", ar: "النجدة!" },
  { jp: "お願いします", rom: "Onegaishimasu", ar: "من فضلك" },
  { jp: "初めまして", rom: "Hajimemashite", ar: "تشرفت بلقائك" },
  { jp: "どういたしまして", rom: "Dou itashimashite", ar: "على الرحب والسعة" },
  { jp: "元気ですか？", rom: "Genki desu ka?", ar: "هل أنت بخير؟" },
  { jp: "元気です", rom: "Genki desu", ar: "أنا بخير" },
  { jp: "こんにちは", rom: "Konnichiwa", ar: "مرحباً" },
  { jp: "ありがとう", rom: "Arigatou", ar: "شكراً" },
  { jp: "おはようございます", rom: "Ohayou gozaimasu", ar: "صباح الخير" },
  { jp: "こんばんは", rom: "Konbanwa", ar: "مساء الخير" },
  { jp: "さようなら", rom: "Sayounara", ar: "إلى اللقاء" },
  { jp: "おやすみなさい", rom: "Oyasuminasai", ar: "تصبح على خير" },
  { jp: "すみません", rom: "Sumimasen", ar: "عذراً / لو سمحت" },
  { jp: "はい", rom: "Hai", ar: "نعم" },
  { jp: "いいえ", rom: "Iie", ar: "لا" },
  { jp: "わかります", rom: "Wakarimasu", ar: "أفهم" },
  { jp: "わかりません", rom: "Wakarimasen", ar: "لا أفهم" },
  { jp: "日本語が少し話せます", rom: "Nihongo ga sukoshi hanasemasu", ar: "أستطيع التحدث باليابانية قليلاً" },
  { jp: "これはいくらですか？", rom: "Kore wa ikura desu ka?", ar: "كم سعر هذا؟" },
  { jp: "トイレはどこですか？", rom: "Toire wa doko desu ka?", ar: "أين دورة المياه؟" },
  { jp: "助けてください！", rom: "Tasukete kudasai!", ar: "النجدة!" },
  { jp: "お願いします", rom: "Onegaishimasu", ar: "من فضلك" },
  { jp: "初めまして", rom: "Hajimemashite", ar: "تشرفت بلقائك" },
  { jp: "どういたしまして", rom: "Dou itashimashite", ar: "على الرحب والسعة" },
  { jp: "元気ですか？", rom: "Genki desu ka?", ar: "هل أنت بخير؟" },
  { jp: "元気です", rom: "Genki desu", ar: "أنا بخير" }
];